show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: thelehhman/texture

permalink: /posts/:title/
texture:
  title: Bedinur Atascan
  tagline: Computer Engineering
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false
  disqus_shortname: bedinur-atascan
  analytics_id: 'UA-162821531-1'


  # generate social links in footer
  social_links:
    github:  bedinuratascan
    linkedIn: in/bedinuratascan
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
